// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlzekyiwgawxtfzoufgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsemVreWl3Z2F3eHRmem91Zmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MDUxOTMsImV4cCI6MjA5MTE4MTE5M30.rp_G8khvScCvGLl3bNv7L2nkLvY6dKtU2yG0zsQV3KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});